### ISSUE TITLE
Remove extraneous dependencies

### ISSUE THREAD

**Issue by bost-ty** [Qiming-Liu/srtparse.js#1]
Hello! Thank you for this package.

When installed in a fresh project, over 500 dependencies are installed. I believe this is a result of including large packages like Babel. 

Are there any plans for a release with a smaller footprint?

Thank you!

**Comment by bost-ty** [comment]
(If they are dev dependencies, setting them as such may fix this issue.)

**Comment by Qiming-Liu** [comment]
Thanks, I'll have a look at it.

**Comment by Qiming-Liu** [comment]
Done, thanks for the help, v1.0.8 released now with that feature.

**Comment by bost-ty** [comment]
I see the change. Thank you!
